import {
  Bell,
  Blocks,
  BookOpen,
  Box,
  Building,
  Calendar,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Contact2,
  Delete,
  Drill,
  Edit,
  FileDown,
  HeartHandshake,
  HelpCircle,
  Home,
  Indent,
  LayoutDashboard,
  LayoutList,
  ListChecks,
  ListTodo,
  LogOut,
  Megaphone,
  Menu,
  Newspaper,
  Outdent,
  Package,
  PanelLeftOpen,
  PanelRightOpen,
  PenBoxIcon,
  Pencil,
  Plus,
  QrCode,
  Rocket,
Settings,
  Ship,
  Siren,
  StickyNote,
  UserCog,
  UsersRound,
  Volume2,
  Wallet,
  Workflow,
  X,
} from "lucide-react";

export const icon = {
  home: <Home />,
  in: <Indent />,
  out: <Outdent />,
  dashboard: <LayoutDashboard />,
  dashboardSmall: <LayoutDashboard className={`c-w-4`} fill="currentColor" />,
  dashboardSmallTransparent: <LayoutDashboard className={`c-w-4`} />,
  inspect: <ListTodo />,
  qr: <QrCode />,
  maintenance: <Drill />,
  schedule: <Calendar />,
  transaction: <ListChecks />,
  master_data: <PenBoxIcon />,
  manage_user: <UserCog />,
  notification: <Bell />,
  profile: <Contact2 />,
  pencil: <Pencil />,
  plus: <Plus />,
  bell: <Bell />,
  bellSmall: <Bell className={`c-w-4`} fill="currentColor" />,
  bellSmallTransparent: <Bell className={`c-w-4`} />,
  help: <HelpCircle />,
  user: <UsersRound />,
  userSmall: <UsersRound className={`c-w-4`} fill="currentColor" />,
  userSmallTransparent: <UsersRound className={`c-w-4`} />,
  workflow: <Workflow />,
  layout: <LayoutList />,
  right: <ChevronRight />,
  left: <ChevronLeft />,
  down: <ChevronDown />,
  setting: <Settings />,
  settingSmall: <Settings className={`c-w-4`} fill="currentColor" />,
  settingSmallTransparent: <Settings className={`c-w-4`} />,
  article: <Newspaper />,
  menuOpen: <PanelRightOpen />,
  menuClose: <PanelLeftOpen />,
  building: <Building />,
  box: <Box />,
  package: <Package />,
  block: <Blocks />,
  megaphone: <Megaphone />,
  policy: <Siren />,
  ship: <Ship />,
  heart: <HeartHandshake />,
  note: <StickyNote />,
  volume: <Volume2 />,
  wallet: <Wallet />,
  download: <FileDown />,
  menu: <Menu />,
  close: <X />,
  logout: <LogOut />,
  logoutSmall: <LogOut className={`c-w-4`} fill="currentColor" />,
  logoutSmallTransparent: <LogOut className={`c-w-4`} />,
  releaseSmall: <Rocket className={`c-w-4`} fill="currentColor" />,
  releaseSmallTransparent: <Rocket className={`c-w-4`} />,
  newsSmall: <BookOpen className={`c-w-4`} fill="currentColor" />,
  newsSmallTransparent: <BookOpen className={`c-w-4`} />,
  scan: (
    <svg
      width="28"
      height="28"
      viewBox="0 0 28 28"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M27.5 20V27.5H0.5V20H3.5V24.5H24.5V20H27.5ZM0.5 12.5H27.5V15.5H0.5V12.5ZM27.5 8H24.5V3.5H3.5V8H0.5V0.5H27.5V8Z"
        fill="white"
      />
    </svg>
  ),
  delete: <Delete />,
  update: <Edit />,
};
