import { Bell, Calendar, ChevronRight, UsersRound, ChevronDown, Contact2, Drill, HelpCircle, Home, LayoutList, ListChecks, ListTodo, PenBoxIcon, QrCode, UserCog, Workflow, Settings, Newspaper, PanelRightOpen, PanelLeftOpen, LayoutDashboard, Building, Box, Package, Blocks, Megaphone, MousePointerSquare, Siren, Ship, HeartHandshake, StickyNote, Volume2, Wallet, FileDown, Menu, X, LogOut, Rocket, BookOpen } from "lucide-react";

export const icon = {
  home: <Home />,
  dashboard: <LayoutDashboard />,
  dashboardSmall: <LayoutDashboard className={`c-w-4`} fill="currentColor" />,
  dashboardSmallTransparent: <LayoutDashboard className={`c-w-4`} />,
  inspect: <ListTodo />,
  qr: <QrCode />,
  maintenance: <Drill />,
  schedule: <Calendar />,
  transaction: <ListChecks />,
  master_data: <PenBoxIcon />,
  manage_user: <UserCog />,
  notification: <Bell />,
  profile: <Contact2 />,
  bell: <Bell />,
  bellSmall: <Bell className={`c-w-4`} fill="currentColor"  />,
  bellSmallTransparent: <Bell className={`c-w-4`} />,
  help: <HelpCircle />,
  user: <UsersRound />,
  userSmall: <UsersRound className={`c-w-4`} fill="currentColor" />,
  userSmallTransparent: <UsersRound className={`c-w-4`} />,
  workflow: <Workflow />,
  layout: <LayoutList />,
  right: <ChevronRight />,
  down: <ChevronDown />,
  setting: <Settings />,
  settingSmall: <Settings className={`c-w-4`} fill="currentColor" />,
  settingSmallTransparent: <Settings className={`c-w-4`} />,
  article: <Newspaper />,
  menuOpen: <PanelRightOpen />,
  menuClose: <PanelLeftOpen />,
  building: <Building />,
  box: <Box />,
  package: <Package />,
  block: <Blocks />,
  megaphone: <Megaphone />,
  pointer: <MousePointerSquare />,
  policy: <Siren />,
  ship: <Ship />,
  heart: <HeartHandshake />,
  note: <StickyNote />,
  volume: <Volume2 />,
  wallet: <Wallet />,
  download: <FileDown />,
  menu: <Menu />,
  close: <X />,
  logout: <LogOut />,
  logoutSmall: <LogOut className={`c-w-4`} fill="currentColor" />,
  logoutSmallTransparent: <LogOut className={`c-w-4`} />,
  releaseSmall: <Rocket className={`c-w-4`} fill="currentColor" />,
  releaseSmallTransparent: <Rocket className={`c-w-4`} />,
  newsSmall: <BookOpen className={`c-w-4`} fill="currentColor" />,
  newsSmallTransparent: <BookOpen className={`c-w-4`} />,
};


